version: '3'

services:
  mongo:
    image: mongo
    container_name: mongo_db
    ports:
      - 27017:27017

  mongo-express:
    image: mongo-express
    container_name: mongo_UI
    ports:
      - 8081:8081
    depends_on:
      - mongo