name: Docker push

on:
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-20.04

    steps:
      - name: get code
        uses: actions/checkout@v2

      - name: get java
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '11'

      - name: build jar file
        run: mvn clean install

      - name: Docker login
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: build and push
        uses: docker/build-push-action@v2
        with:
          context: docker-compose-prod.yml
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/alm-solo-project:v1.2

      - name: upload jar file
        uses: actions/upload-artifact@v2
        with:
          name: alm-solo-project.jar
          path: target/*.jar